# print("Hello from lesson 13")
# mylist = []
# mylist.append("apple")
# mylist.append("bread")
# mylist.append("carrots")
# mylist.append("dates")
# mylist.append("eggs")
# mylist.append("apple")
# mylist.append("bread")
# mylist.append("carrots")
# mylist.append("dates")
# mylist.append("eggs")
# mylist.append("flour")
# mylist.append("grapes")
# mylist.append("honey")
# print(mylist)
# print(mylist[0])
# print(mylist[1])
# print(mylist[2])
# print(mylist[3])
# print(mylist[4])
# print(mylist[5])
# print(mylist[6])
# print(mylist[7])
# mylist[7]="herbs"
# print(mylist)
# print(mylist[0])
# print(mylist[1])
# print(mylist[2])
# print(mylist[3])
# print(mylist[4])
# print(mylist[5])
# print(mylist[6])
# print(mylist[7])
# mylist.append("ice")
# mylist.insert(1,"bannana")
# print(mylist)
# print(mylist[0])
# print(mylist[1])
# print(mylist[2])
# print(mylist[3])
# print(mylist[4])
# print(mylist[5])
# print(mylist[6])
# print(mylist[7])
# print(mylist[8])
# print(mylist[14])
classlist = []
classlist.append("aiden")
classlist.append("Farooq")
classlist.append("Andric")
classlist.append("Jonas")
classlist.append("Caleb")
classlist.append("Dylann")
classlist.append("gabriel")
classlist.append("Jaden")
classlist.append("Jaden")
classlist.append("Jasiel")
classlist.append("Jivesh")
classlist.append("kalen")
classlist.append("Kristoff")
classlist.append("Jove")
classlist.append("")